server {
    listen 80;
    server_name www.awalon.top;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.awalon.top;

    ssl_certificate /etc/letsencrypt/live/www.awalon.top/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.awalon.top/privkey.pem;

    location /ws {
        proxy_pass http://127.0.0.1:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 600s;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
