// mobile/miniprogram/skins.js

const CDN = 'https://www.awalon.top/mp-assets';
const DEFAULT_SKIN_ID = 'dark-gold';

function buildSkinAssetUrl(skinId, assetName) {
  if (skinId === DEFAULT_SKIN_ID) {
    const defaults = {
      'home-bg': `${CDN}/in-game-bg-optimized.jpg?v=2`,
      'in-game-bg': `${CDN}/in-game-bg-optimized.jpg?v=2`,
      table: `${CDN}/table.png?v=8`,
      'quest-success': `${CDN}/quest-success-420x300.png?v=5`,
      'quest-fail': `${CDN}/quest-failed-420x300.png?v=5`,
      'role-base': `${CDN}/role-split`,
    };
    return defaults[assetName] || '';
  }
  if (assetName === 'role-base') return `${CDN}/skins/${skinId}/role-split`;
  return `${CDN}/skins/${skinId}/${assetName}`;
}

const ROLE_FILE_MAP = {
  '梅林':    'merlin',
  '派西维尔': 'percival',
  '忠臣':    'arthur_loyal',
  '亚瑟的忠臣': 'arthur_loyal',
  '刺客':    'assassin',
  '莫甘娜':  'morgana',
  '莫德雷德': 'mordred',
  '奥伯伦':  'oberon',
  '爪牙':    'minion',
  '兰斯洛特（正义）': 'lancelot_good',
  '兰斯洛特（邪恶）': 'lancelot_evil',
};

const SKINS = [
  {
    id: 'dark-gold',
    name: '暗夜金',
    isDark: true,
    cssClass: 'theme-dark-gold',
    colors: { bg: '#0f1115', panel: 'rgba(19,23,31,0.82)', accent: '#d9b36b' },
    homeBg:       buildSkinAssetUrl(DEFAULT_SKIN_ID, 'home-bg'),
    inGameBg:     buildSkinAssetUrl(DEFAULT_SKIN_ID, 'in-game-bg'),
    table:        buildSkinAssetUrl(DEFAULT_SKIN_ID, 'table'),
    questSuccess: buildSkinAssetUrl(DEFAULT_SKIN_ID, 'quest-success'),
    questFail:    buildSkinAssetUrl(DEFAULT_SKIN_ID, 'quest-fail'),
    imageBase: null,
    vars: {
      '--aw-bg':               '#0f1115',
      '--aw-bg-2':             '#161b24',
      '--aw-panel':            'rgba(19,23,31,0.72)',
      '--aw-panel-border':     'rgba(255,255,255,0.10)',
      '--aw-panel-border-width': '1rpx',
      '--aw-panel-shadow':     'none',
      '--aw-text':             '#eef1f7',
      '--aw-subtext':          '#aeb6c7',
      '--aw-accent':           '#d9b36b',
      '--aw-accent-text':      '#1a1200',
      '--aw-nav-bg':           'rgba(12,16,24,0.88)',
      '--aw-nav-border':       'rgba(255,255,255,0.08)',
      '--aw-chip-on-bg':       'rgba(217,179,107,0.18)',
      '--aw-chip-on-border':   'rgba(217,179,107,0.45)',
      '--aw-chip-on-text':     '#d9b36b',
      '--aw-btn-ghost-border': 'rgba(255,255,255,0.22)',
      '--aw-btn-ghost-text':   '#eef1f7',
      '--aw-input-bg':         'rgba(255,255,255,0.06)',
      '--aw-input-border':     'rgba(255,255,255,0.14)',
      '--aw-bg-image':         'none',
    },
  },
  {
    id: 'celestial',
    name: '仙境',
    isDark: false,
    cssClass: 'theme-celestial',
    colors: { bg: '#e8d8b0', panel: 'rgba(248,238,210,0.90)', accent: '#c8902a' },
    get homeBg()       { return buildSkinAssetUrl(this.id, 'home-bg.jpg'); },
    get inGameBg()     { return buildSkinAssetUrl(this.id, 'in-game-bg.jpg'); },
    get table()        { return buildSkinAssetUrl(this.id, 'table.png'); },
    get questSuccess() { return buildSkinAssetUrl(this.id, 'quest-success.png'); },
    get questFail()    { return buildSkinAssetUrl(this.id, 'quest-fail.png'); },
    imageBase: buildSkinAssetUrl('celestial', 'role-base'),
    vars: {
      '--aw-bg':               '#e8d8b0',
      '--aw-bg-2':             '#dcc89a',
      '--aw-panel':            'rgba(248,238,210,0.90)',
      '--aw-panel-border':     'rgba(196,158,72,0.55)',
      '--aw-panel-border-width': '1rpx',
      '--aw-panel-shadow':     '0 0 0 1rpx rgba(196,158,72,0.20), 0 4rpx 20rpx rgba(140,100,20,0.18)',
      '--aw-text':             '#2c1a08',
      '--aw-subtext':          '#7a5830',
      '--aw-accent':           '#c8902a',
      '--aw-accent-text':      '#fff8ec',
      '--aw-nav-bg':           'rgba(232,215,168,0.94)',
      '--aw-nav-border':       'rgba(196,158,72,0.40)',
      '--aw-chip-on-bg':       'rgba(200,144,42,0.20)',
      '--aw-chip-on-border':   'rgba(200,144,42,0.60)',
      '--aw-chip-on-text':     '#7a4e10',
      '--aw-btn-ghost-border': 'rgba(196,158,72,0.55)',
      '--aw-btn-ghost-text':   '#5c3810',
      '--aw-input-bg':         'rgba(255,248,228,0.80)',
      '--aw-input-border':     'rgba(196,158,72,0.40)',
      '--aw-bg-image':         'none',
    },
  },
  {
    id: 'ink-wash',
    name: '水墨古风',
    isDark: false,
    cssClass: 'theme-ink-wash',
    colors: { bg: '#f4f0ea', panel: 'rgba(244,240,234,0.88)', accent: '#2d2520' },
    get homeBg()       { return buildSkinAssetUrl(this.id, 'home-bg.jpg'); },
    get inGameBg()     { return buildSkinAssetUrl(this.id, 'in-game-bg.jpg'); },
    get table()        { return buildSkinAssetUrl(this.id, 'table.png'); },
    get questSuccess() { return buildSkinAssetUrl(this.id, 'quest-success.png'); },
    get questFail()    { return buildSkinAssetUrl(this.id, 'quest-fail.png'); },
    imageBase: buildSkinAssetUrl('ink-wash', 'role-base'),
    vars: {
      '--aw-bg':               '#f4f0ea',
      '--aw-bg-2':             '#e8e2d8',
      '--aw-panel':            'rgba(244,240,234,0.88)',
      '--aw-panel-border':     'rgba(0,0,0,0.12)',
      '--aw-text':             '#1a1612',
      '--aw-subtext':          '#6b5f54',
      '--aw-accent':           '#2d2520',
      '--aw-accent-text':      '#f4f0ea',
      '--aw-nav-bg':           'rgba(234,230,220,0.92)',
      '--aw-nav-border':       'rgba(0,0,0,0.08)',
      '--aw-chip-on-bg':       'rgba(45,37,32,0.12)',
      '--aw-chip-on-border':   'rgba(45,37,32,0.40)',
      '--aw-chip-on-text':     '#2d2520',
      '--aw-btn-ghost-border': 'rgba(0,0,0,0.22)',
      '--aw-btn-ghost-text':   '#2d2520',
      '--aw-input-bg':         'rgba(255,255,255,0.70)',
      '--aw-input-border':     'rgba(0,0,0,0.16)',
      '--aw-bg-image':         'none',
    },
  },
  {
    id: 'cyber-neon',
    name: '赛博霓虹',
    isDark: true,
    cssClass: 'theme-cyber-neon',
    colors: { bg: '#0d0b16', panel: 'rgba(20,16,40,0.88)', accent: '#e879f9' },
    get homeBg()       { return buildSkinAssetUrl(this.id, 'home-bg.jpg'); },
    get inGameBg()     { return buildSkinAssetUrl(this.id, 'in-game-bg.jpg'); },
    get table()        { return buildSkinAssetUrl(this.id, 'table.png'); },
    get questSuccess() { return buildSkinAssetUrl(this.id, 'quest-success.png'); },
    get questFail()    { return buildSkinAssetUrl(this.id, 'quest-fail.png'); },
    imageBase: buildSkinAssetUrl('cyber-neon', 'role-base'),
    vars: {
      '--aw-bg':               '#0d0b16',
      '--aw-bg-2':             '#14102a',
      '--aw-panel':            'rgba(20,16,40,0.88)',
      '--aw-panel-border':     'rgba(232,121,249,0.15)',
      '--aw-text':             '#f0e8ff',
      '--aw-subtext':          '#b097d8',
      '--aw-accent':           '#e879f9',
      '--aw-accent-text':      '#1a0020',
      '--aw-nav-bg':           'rgba(10,6,22,0.92)',
      '--aw-nav-border':       'rgba(232,121,249,0.12)',
      '--aw-chip-on-bg':       'rgba(232,121,249,0.15)',
      '--aw-chip-on-border':   'rgba(232,121,249,0.45)',
      '--aw-chip-on-text':     '#e879f9',
      '--aw-btn-ghost-border': 'rgba(232,121,249,0.30)',
      '--aw-btn-ghost-text':   '#f0e8ff',
      '--aw-input-bg':         'rgba(255,255,255,0.05)',
      '--aw-input-border':     'rgba(232,121,249,0.20)',
      '--aw-bg-image':         'none',
    },
  },
  {
    id: 'dark-dungeon',
    name: '邪恶铭刻',
    isDark: true,
    cssClass: 'theme-dark-dungeon',
    colors: { bg: '#0c0802', panel: 'rgba(28,18,6,0.96)', accent: '#c8902a' },
    get homeBg()       { return buildSkinAssetUrl(this.id, 'home-bg.jpg'); },
    get inGameBg()     { return buildSkinAssetUrl(this.id, 'in-game-bg.jpg'); },
    get table()        { return buildSkinAssetUrl(this.id, 'table.png'); },
    get questSuccess() { return buildSkinAssetUrl(this.id, 'quest-success.png'); },
    get questFail()    { return buildSkinAssetUrl(this.id, 'quest-fail.png'); },
    imageBase: buildSkinAssetUrl('dark-dungeon', 'role-base'),
    fontUrl: `${CDN}/skins/dark-dungeon/fonts/title.woff2`,
    vars: {
      '--aw-bg':               '#0c0802',
      '--aw-bg-2':             '#180f04',
      '--aw-panel':            'rgba(22,14,4,0.62)',
      '--aw-panel-border':     'rgba(185,138,52,0.65)',
      '--aw-panel-border-width': '2rpx',
      '--aw-panel-shadow':     '0 0 0 1rpx rgba(185,138,52,0.25), 0 6rpx 28rpx rgba(0,0,0,0.75), inset 0 0 48rpx rgba(0,0,0,0.55)',
      '--aw-text':             '#edd9aa',
      '--aw-subtext':          '#9a7848',
      '--aw-accent':           '#c8902a',
      '--aw-accent-text':      '#0c0802',
      '--aw-nav-bg':           'rgba(8,5,1,0.98)',
      '--aw-nav-border':       'rgba(185,138,52,0.45)',
      '--aw-chip-on-bg':       'rgba(200,144,42,0.22)',
      '--aw-chip-on-border':   'rgba(200,144,42,0.70)',
      '--aw-chip-on-text':     '#d4a043',
      '--aw-btn-ghost-border': 'rgba(185,138,52,0.55)',
      '--aw-btn-ghost-text':   '#edd9aa',
      '--aw-input-bg':         'rgba(255,220,140,0.05)',
      '--aw-input-border':     'rgba(185,138,52,0.35)',
      '--aw-bg-image':         'none',
      '--aw-dd-gold-hi':       'rgba(185,138,52,0.90)',
      '--aw-dd-gold-mid':      'rgba(185,138,52,0.55)',
      '--aw-dd-gold-lo':       'rgba(185,138,52,0.22)',
    },
  },
  {
    id: 'abyss',
    name: '深渊',
    isDark: true,
    cssClass: 'theme-abyss',
    colors: { bg: '#050507', panel: 'rgba(8,8,16,0.92)', accent: '#4060c0' },
    get homeBg()       { return buildSkinAssetUrl(this.id, 'home-bg.jpg'); },
    get inGameBg()     { return buildSkinAssetUrl(this.id, 'in-game-bg.jpg'); },
    get table()        { return buildSkinAssetUrl(this.id, 'table.png'); },
    get questSuccess() { return buildSkinAssetUrl(this.id, 'quest-success.png'); },
    get questFail()    { return buildSkinAssetUrl(this.id, 'quest-fail.png'); },
    imageBase: buildSkinAssetUrl('abyss', 'role-base'),
    vars: {
      '--aw-bg':               '#050507',
      '--aw-bg-2':             '#0a0a12',
      '--aw-panel':            'rgba(8,8,16,0.92)',
      '--aw-panel-border':     'rgba(100,120,180,0.12)',
      '--aw-text':             '#d0d8f0',
      '--aw-subtext':          '#7080a8',
      '--aw-accent':           '#4060c0',
      '--aw-accent-text':      '#ffffff',
      '--aw-nav-bg':           'rgba(2,2,8,0.95)',
      '--aw-nav-border':       'rgba(80,100,160,0.10)',
      '--aw-chip-on-bg':       'rgba(64,96,192,0.18)',
      '--aw-chip-on-border':   'rgba(64,96,192,0.45)',
      '--aw-chip-on-text':     '#4060c0',
      '--aw-btn-ghost-border': 'rgba(80,100,160,0.30)',
      '--aw-btn-ghost-text':   '#d0d8f0',
      '--aw-input-bg':         'rgba(255,255,255,0.04)',
      '--aw-input-border':     'rgba(80,100,160,0.16)',
      '--aw-bg-image':         'none',
    },
  },
];

function getSkin(id) {
  return SKINS.find((s) => s.id === id) || SKINS[0];
}

function roleImageFor(role, skinId) {
  const file = ROLE_FILE_MAP[role];
  if (!file) return '';
  const skin = getSkin(skinId);
  const base = (skin && skin.imageBase) ? skin.imageBase : buildSkinAssetUrl(DEFAULT_SKIN_ID, 'role-base');
  return `${base}/${file}.png`;
}

function buildVarString(skin) {
  if (!skin || !skin.vars) return '';
  return Object.entries(skin.vars).map(([k, v]) => `${k}:${v}`).join(';');
}

module.exports = { CDN, DEFAULT_SKIN_ID, SKINS, getSkin, roleImageFor, buildVarString, buildSkinAssetUrl };
