Component({
  properties: {
    tableUrl:            { type: String,  value: 'https://www.awalon.top/mp-assets/table.png?v=8' },
    seats:               { type: Array,   value: [] },
    identityMode:        { type: Boolean, value: false },
    seatNotes:           { type: Object,  value: {} },
    showCenterResult:    { type: Boolean, value: false },
    centerResultText:    { type: String,  value: '' },
    centerResultSub:     { type: String,  value: '' },
    endMedals:           { type: Array,   value: [] },
    isHost:              { type: Boolean, value: false },
    isLeader:            { type: Boolean, value: false },
    isAssassin:          { type: Boolean, value: false },
    phase:               { type: String,  value: '' },
    roomStarted:         { type: Boolean, value: false },
    leaderActionText:    { type: String,  value: '' },
    leaderActionClass:   { type: String,  value: '' },
    leaderActionDisabled:{ type: Boolean, value: false },
    selectedAssassinate: { type: String,  value: '' },
    emojiBubbles:        { type: Object,  value: {} },
  },

  methods: {
    onChooseSeat(e)         { this.triggerEvent('chooseseat',    e.currentTarget.dataset); },
    onSeatTouchStart(e)     { this.triggerEvent('seattouchstart', e.currentTarget.dataset); },
    onSeatTouchEnd()        { this.triggerEvent('seattouchend'); },
    onSeatTouchCancel()     { this.triggerEvent('seattouchcancel'); },
    onTapMedal(e)           { this.triggerEvent('tapmedal',      e.currentTarget.dataset); },
    onRedeal()              { this.triggerEvent('redeal'); },
    onLeaderAction()        { this.triggerEvent('leaderaction'); },
    onStartAssassination()  { this.triggerEvent('startassassination'); },
    onConfirmAssassinate()  { this.triggerEvent('confirmassassinate'); },
    onStartGame()           { this.triggerEvent('startgame'); },
  },
});
